# fly.toml app configuration file generated for wehatescrum on 2024-02-09T17:09:32+05:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'wehatescrum'
primary_region = 'hkg'

[build]

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 512
